<img style="float: left;;" src='../Figures/iteso.jpg' width="50" height="100"/></a>

# <center> <font color= #000047> Repaso de la Librería NumPy</font> </center>


# Operaciones con NumPy

## Aritméticas

Podemos realizar fácilmente aritmeticas como *arreglo con arreglo* , o *escalar con arreglo*. Veamos algunos ejemplos: 

In [1]:
import numpy as np

In [2]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [3]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr_2 = arr + arr

In [6]:
arr_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr_2.shape

(10,)

In [8]:
arr - arr_2

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [9]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
2*arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [13]:
M = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
M**2 #(MxM)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [16]:
a = np.arange(1,10)
a.shape

(9,)

In [17]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
M.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [19]:
M2 = np.arange(2,11).reshape(3,3)
M2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [20]:
# M x M2 (3x3 3x3)
M@M2

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [21]:
np.dot(M,M2)

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [22]:
np.matmul(M,M2)

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [25]:
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.linalg.det(I)

1.0

In [28]:
np.linalg.det(M),np.linalg.det(M2)

(0.0, 0.0)

In [29]:
np.linalg.inv(I)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
M3 = np.array([[2,6],
              [6,7]])

In [31]:
M3

array([[2, 6],
       [6, 7]])

In [32]:
np.dot(M,M3)

ValueError: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

## Funciones universales en los Arreglos

NumPy viene con muchass [funciones universales en los arreglos](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, que son esencialmente operaciones matemáticas que se pueden aplicar al arreglo.<br>Veamos algunas funciones más comunes:

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [35]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [36]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [37]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [38]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [40]:
np.min(arr)

0

In [42]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr.min()

0

In [43]:
arr.argmin()

0

In [44]:
arr.max()

9

In [45]:
arr.argmax()

9

In [46]:
np.random.shuffle(arr)

In [47]:
arr

array([2, 1, 3, 9, 8, 6, 7, 4, 0, 5])

In [48]:
arr.max(), arr.argmax()

(9, 3)

In [49]:
arr.min(), arr.argmin()

(0, 8)

In [50]:
arr.T

array([2, 1, 3, 9, 8, 6, 7, 4, 0, 5])

In [52]:
M.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [53]:
M.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [54]:
a.shape

(9,)

In [56]:
M.shape

(3, 3)

In [57]:
M.dtype

dtype('int32')

## Resumen de Estadística sobre Arreglos

NumPy también ofrece métodos estadísticos como <em> sum </em>, <em> mean </em> y <em> max </em>. 

In [58]:
arr.sum()

45

In [59]:
arr.var()

8.25

In [60]:
arr.std()

2.8722813232690143

In [61]:
arr.min()

0

In [62]:
arr.max()

9

In [63]:
M2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [64]:
M2.sum()

54

In [66]:
arr.shape, M.shape

((10,), (3, 3))

## Lógica para el eje (axis)

Cuando trabajamos con arreglos bidimensionales, debemos considerar filas y columnas. En términos de un arreglo, el eje 0 (cero) es el eje horizontal (filas) y el eje 1 es el eje vertical (columnas). Los valores (0,1) corresponden al orden en el que método <tt> arr.shape </tt> da como salida.

Veamos cómo afecta esto a nuestros cálculos estadísticos resumidos de arriba.


In [67]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
M.sum(axis=0)

array([12, 15, 18])

In [69]:
M.sum(axis=1)

array([ 6, 15, 24])

Dando como entrada <tt>axis=0</tt>, estamos devolviendo la suma del arreglo a lo largo del eje vertical, esencialmente <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

<img src='axis_logic.png' width=400/>

Esto nos dice que <tt>arr_2d</tt> tiene 3 filas y 4 columnas.

En <tt>arr_2d.sum(axis=0)</tt>, se sumó el primer elemento de cada fila, luego el segundo elemento y así sucesivamente.

Entonces, ¿qué debería <tt>arr_2d.sum(axis=1)</tt> regresar?